platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods', :disable_input_output_paths => true

flutter_root = ENV['FLUTTER_ROOT'] || File.expand_path('..', __dir__)
if !File.exist?(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb'))
  flutter_binary = `which flutter`.strip
  flutter_root = File.expand_path('..', File.dirname(flutter_binary)) unless flutter_binary.empty?
end
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
